### ISSUE TITLE
SQL Injection 

### ISSUE THREAD

**Issue by omarsar** [wisebits/url-shortner#1]
## Retrieving Information (Availability)

Before any attack, a hacker would like to know some more information (e.g. schema, tables, attributes, version, etc...) about the database if there is one. After obtaining desired database information then a hacker can test different harmful SQL injections via URL. This can be done if API is not properly configured. (POST, PUT, GET).  

**Random Guessing**: Even if a hacker cannot obtain information about the database they can try conventional or typical used configurations (e.g. "user/:id/admin", "url/:id/password"). 

Example of GET query:
A hacker can test to get a resource like this 
`api/v1/users/a`

The above query is no problem since it get user a. A slight change like 
`api/v1/users/get_me_every_user_that_starts_with_a`

pretending that last value `api/v1/users/get_me_every_user_that_starts_with_a` is a valid query to obtain a ton of users. This can cause an overload for a database if the proper resources are not considered. Example of DB query:

`SELECT * from users`

---
## Updating Information (Integrity and Authentication)

Similarly, if SQL injection is not properly taken care of, an attacker can change information on the go through the URL through the `PUT` request. 

This can have undesired effect such as users not being able to access resources through their accounts. Moreover this impacts the integrity of a service since there might be other resources that were changed. (Solution: maybe backups)

**Comment by soumyaray** [comment]
feel confident this is solved?  :)

**Comment by omarsar** [comment]
Not entirely! But if anything we will have to make it part of the conversation tomorrow. :)
