### ISSUE TITLE
Issue with Test

### ISSUE THREAD

**Issue by omarsar** [wisebits/url-shortner#10]
@soumyaray Here is the issue I explained in class. I have commented out the lines that are not functioning... Basically the issue lies in this line: 
`new_url.add_permission(status: 'testing', description: 'anything')`. 
All the tests run, except this one, which is generating a "Type Mismatch exception." 

``` ruby
# directory: spec/url_spec.rb
describe 'Finding existing URLs' do
    it 'HAPPY: should find an existing URL' do
      new_url = Url.new(title: 'test23')
      new_url.url = 'http://test23.com'
      new_url.shorturl = new_url.url
      new_url.save

      #new_permissions = (1..3).map do |i|
      #new_url.add_permission(status: 'testing', description: 'anything')
      #end

      get "/api/v1/urls/#{new_url.id}"
      _(last_response.status).must_equal 200

      results = JSON.parse(last_response.body)
      _(results['data']['id']).must_equal new_url.id

      #3.times do |i|
      #  _(results['relationships'][i]['id']).must_equal new_permissions[i].id
      #end
    end
```

CC: @adi-botak- @nweat #

**Comment by soumyaray** [comment]
could you copy/paste the entire error message (as long as it might be)?  i'll try to play with this later tonight.

**Comment by omarsar** [comment]
@soumyaray Here is the error:

Run options: --seed 55575

# Running:

.E.WARN: tilt autoloading 'tilt/haml' in a non thread-safe way; explicit require 'tilt/haml' suggested.
...

Finished in 0.271924s, 22.0650 runs/s, 36.7749 assertions/s.

  1) Error:
URL resource calls::Finding existing URLs#test_0001_HAPPY: should find an existing URL:
Sequel::DatabaseError: SQLite3::MismatchException: datatype mismatch
    /home/ellfae/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/sqlite3-1.3.11/lib/sqlite3/statement.rb:108:in `step'
    /home/ellfae/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/sqlite3-1.3.11/lib/sqlite3/statement.rb:108:in`block in each'
    /home/ellfae/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/sqlite3-1.3.11/lib/sqlite3/statement.rb:107:in `loop'
    /home/ellfae/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/sqlite3-1.3.11/lib/sqlite3/statement.rb:107:in`each'
    /home/ellfae/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/sqlite3-1.3.11/lib/sqlite3/database.rb:158:in `to_a'
    /home/ellfae/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/sqlite3-1.3.11/lib/sqlite3/database.rb:158:in`block in execute'
    /home/ellfae/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/sqlite3-1.3.11/lib/sqlite3/database.rb:95:in `prepare'
    /home/ellfae/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/sqlite3-1.3.11/lib/sqlite3/database.rb:134:in`execute'
    /home/ellfae/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/sequel-4.33.0/lib/sequel/adapters/sqlite.rb:189:in `block (2 levels) in _execute'
    /home/ellfae/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/sequel-4.33.0/lib/sequel/database/logging.rb:35:in`log_yield'
    /home/ellfae/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/sequel-4.33.0/lib/sequel/adapters/sqlite.rb:189:in `block in _execute'
    /home/ellfae/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/sequel-4.33.0/lib/sequel/database/connecting.rb:251:in`block in synchronize'
    /home/ellfae/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/sequel-4.33.0/lib/sequel/connection_pool/threaded.rb:101:in `hold'
    /home/ellfae/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/sequel-4.33.0/lib/sequel/database/connecting.rb:251:in`synchronize'
    /home/ellfae/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/sequel-4.33.0/lib/sequel/adapters/sqlite.rb:180:in `_execute'
    /home/ellfae/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/sequel-4.33.0/lib/sequel/adapters/sqlite.rb:151:in`execute_insert'
    /home/ellfae/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/sequel-4.33.0/lib/sequel/dataset/actions.rb:968:in `execute_insert'
    /home/ellfae/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/sequel-4.33.0/lib/sequel/dataset/actions.rb:338:in`insert'
    /home/ellfae/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/sequel-4.33.0/lib/sequel/model/base.rb:1885:in `_insert_raw'
    /home/ellfae/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/sequel-4.33.0/lib/sequel/model/base.rb:1867:in`_insert'
    /home/ellfae/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/sequel-4.33.0/lib/sequel/model/base.rb:1928:in `block (2 levels) in _save'
    /home/ellfae/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/sequel-4.33.0/lib/sequel/model/base.rb:1146:in`around_create'
    /home/ellfae/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/sequel-4.33.0/lib/sequel/model/base.rb:1925:in `block in _save'
    /home/ellfae/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/sequel-4.33.0/lib/sequel/model/base.rb:1146:in`around_save'
    /home/ellfae/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/sequel-4.33.0/lib/sequel/model/base.rb:1921:in `_save'
    /home/ellfae/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/sequel-4.33.0/lib/sequel/model/base.rb:1573:in`block (2 levels) in save'
    /home/ellfae/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/sequel-4.33.0/lib/sequel/model/base.rb:2075:in `block in checked_transaction'
    /home/ellfae/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/sequel-4.33.0/lib/sequel/database/transactions.rb:141:in`_transaction'
    /home/ellfae/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/sequel-4.33.0/lib/sequel/database/transactions.rb:115:in `block in transaction'
    /home/ellfae/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/sequel-4.33.0/lib/sequel/database/connecting.rb:251:in`block in synchronize'
    /home/ellfae/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/sequel-4.33.0/lib/sequel/connection_pool/threaded.rb:105:in `hold'
    /home/ellfae/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/sequel-4.33.0/lib/sequel/database/connecting.rb:251:in`synchronize'
    /home/ellfae/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/sequel-4.33.0/lib/sequel/database/transactions.rb:101:in `transaction'
    /home/ellfae/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/sequel-4.33.0/lib/sequel/model/base.rb:2075:in`checked_transaction'
    /home/ellfae/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/sequel-4.33.0/lib/sequel/model/base.rb:1573:in `block in save'
    /home/ellfae/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/sequel-4.33.0/lib/sequel/model/base.rb:2063:in`checked_save_failure'
    /home/ellfae/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/sequel-4.33.0/lib/sequel/model/base.rb:1573:in `save'
    /home/ellfae/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/sequel-4.33.0/lib/sequel/model/associations.rb:2049:in`block in def_one_to_many'
    /home/ellfae/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/sequel-4.33.0/lib/sequel/model/associations.rb:2208:in `add_associated_object'
    /home/ellfae/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/sequel-4.33.0/lib/sequel/model/associations.rb:1789:in`block in def_association_instance_methods'
    specs/url_spec.rb:46:in `block (4 levels) in <main>'
    specs/url_spec.rb:45:in`each'
    specs/url_spec.rb:45:in `map'
    specs/url_spec.rb:45:in`block (3 levels) in <main>'

6 runs, 10 assertions, 0 failures, 1 errors, 0 skips

**Comment by soumyaray** [comment]
Hi, which branch should I be testing on?  I notice that the tests in the master branch are using wrong attribute names for your Url model.

**Comment by omarsar** [comment]
It is master branch, the url creation is okay. For assignment,  i just use the shortcut `.url` and `.shorturl` for `full_url` and `short_url`, repsectively

**Comment by omarsar** [comment]
@soumyaray the other guys figured it out.. it still doesn't work on my machine, but I will see what is going on locally. I will close this issue now.

**Comment by soumyaray** [comment]
ok. i recommend you (and your whole team) all do a `bundle install` and `bundle exec rake spec` to make sure you are all using the same version of all gems (from Gemfile.lock)!
